---
# tasks file for haproxy
- name: install haproxy
  yum: name=haproxy state=present

- name: uncomment line from rsyslog
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "#$ModLoad imudp", 'line': "$Modload imdup"}
    - {'regexp': "#$UDPServerRun 514", 'line': "$UPDServerRun 514"}

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: start haproxy
  service: name=haproxy state=started enabled=yes

- name: adding port
  firewalld:
   port: 514/tcp
   permanent: true
   zone: public
   state: enabled

- name: reload port list
  command: firewall-cmd --reload
