---
# tasks file for httpd
- name: uninstalling httpd
  package: name=httpd state=absent

- name: installing httpd
  package: name=httpd state=present

- name: starting httpd
  service: name=httpd state=started

- name: adding port
  firewalld:
    service: http
    permanent: true
    state: enabled
    zone: public

- name: reloading firewall 
  command: firewall-cmd --reload

#- name: inserting lines into httpd
 # template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
 



